openapi: 3.0.0
info:
  title: CyberDoc Auth API
  version: 1.0.0
paths:
  /users/profile:
    get:
      summary: Connected user profile
      description: Get connected user profile
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/profile"
        "500":
          description: Internal Error
    delete:
      summary: Delete user's account
      description: Delete user's account
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/deleteProfile"
        "500":
          description: Internal Error
          
          
components:
  schemas:
    profile:
      example: 
        success: true
        msg: "Success"
        user: 
          role: "collaborater"
          updated_at: "2020-09-22T11:31:20.714Z"
          created_at: "2020-09-22T11:30:54.556Z"
          _id: "65af88e0-4d6f-80da-1cab-6ef5db2c719e"
          firstname: "Flavien"
          lastname: "JOURDREN"
          email: "flavien.jourdren@gmail.com"
      description: User's profile
      type: object
      required:
        - success
        - msg
        - user
      properties:
        success:
          type: boolean
          example: true
          description: Action successed
        msg:
          type: string
          example: "Success"
          description: Send to HTTP client a message / an error
        user:
          type: object
          properties:
            role:
              description: The file to upload.
              type: string
              format: binary
            updated_at:
              description: User's account updated_at
              type: string
              format: date-time
            created_at:
              description: User's account created at
              type: string
              format: date-time
            _id:
              description: ID
              type: string
            firstname:
              description: User's firstname
              type: string
            lastname:
              description: User's lastname
              type: string
            email:
              description: User's email
              type: string
          description: User's profile
    deleteProfile:
      example: 
        success: true
        msg: "User deleted"
      description: Inform the user about what the server did to data
      type: object
      required:
        - success
        - msg
      properties:
        success:
          type: boolean
          example: true
          description: Action successed
        msg:
          type: string
          example: "User deleted"
          description: Send to HTTP client a message / an error