- hosts: glvps
  name: Install docker 
  gather_facts: false
  become: true
  tasks:

  - name: create docker-compose-files directory if it does not exist
    file:
      path: /etc/docker-compose-files/startup
      state: directory
      mode: '0755'

  - name: deploy docker compose template
    template:
      src: /etc/ansible/playbooks/docker-compose.yml
      dest: /etc/docker-compose-files/startup/docker-compose.yml
      owner: root
      group: root
      mode: 0611
      backup: yes

  - name: create traefik hot directory
    file:
      path: /etc/traefik/conf.d
      state: directory
      mode: '0755'
  
  - name: deploy traefik components
    template:
      src: /etc/ansible/playbooks/traefik-void-file
      dest: /etc/traefik/conf.d/traefik-void-file
      owner: root
      group: root
      mode: 0611
      backup: yes
  
  - name: deploy traefik acme.json void file
    template:
      src: /etc/ansible/playbooks/traefik-void-file
      dest: /etc/traefik/acme.json
      owner: root
      group: root
      mode: 0600
      backup: yes

  - name: create onlyoffice hot directory
    file:
      path: /home/centos/workspace/cyberdoc/onlyoffice/logs
      state: directory
      mode: '0755'

  - name: create jenkins hot directory
    file:
      path: /etc/jenkins
      state: directory
      mode: '0777'

  - name: create sonarqube hot directory
    file:
      path: /etc/sonarqube
      state: directory
      mode: '0755'

  - name: run playbook
    docker_compose:
      project_src: /etc/docker-compose-files/startup/
