version: "3"
services:

  portainer:
    image: portainer/portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.http.routers.portainerrouter.rule=Host(`portainer.fulgen.fr`)"
      - "traefik.http.services.portainerservice.loadbalancer.server.port=9000"

  traefik:
    image: traefik:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/docker_mount/traefik/conf.d:/etc/traefik/conf.d
    network_mode: host
    command:
      - "--global.sendanonymoususage=false" # désactivation de l'envoi de donnée
      - "--global.checknewversion=false" # désactive le check de mise à jour
      - "--accesslog=true" # logs d'accès
      - "--api=true" # activer l'api
      - "--api.insecure=true" # Activer pour exposer l'api sur 8080
      - "--api.dashboard=true" # Pour activer le dashboard
      - "--log.level=INFO"
      - "--providers.docker=true"
    ####
      #- "--providers.docker.exposedbydefault=true" # en cas de debug uniquement
      - "--providers.file.directory=/etc/traefik/conf.d/" # Permets de charger les configurations dans le répertoire (tout les yaml et toml)
      - "--providers.file.watch=true" # Permets de surveiller le répertoire précédent pour charger dynamiquement les configurations
      - "--entrypoints.web.address=:80" # Création de l'entrypoint nommé web sur le port 80
      - "--entrypoints.websecure.address=:443" # Création de l'entrypoint nommé websecure sur le port 443
     # - "--entrypoints.proxy.address=:8088" # Création de l'entrypoint nommé websecure sur le port 8088
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefikrouter.rule=Host(`traefik.fulgen.fr`)"
      - "traefik.http.services.traefikservice.loadbalancer.server.port=8080" 

  # testing
  #nginx:
  #  image: nginx
  #  volumes:
  #    - /home/docker_mount/nginx_dk:/usr/share/nginx/html:ro
  #  labels:
  #    - "traefik.enable=true"
  #    - "traefik.http.routers.nginxrouter.rule=Host(`cyberdoc.fulgen.fr`)"
  #    - "traefik.http.services.nginxservice.loadbalancer.server.port=80"    

  jenkins:
    image: jenkins/jenkins
    volumes:
      - /etc/jenkins:/var/jenkins_home 
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jenkinsrouter.entrypoints=web"
      - "traefik.http.routers.jenkinsrouter.rule=Host(`jenkins.fulgen.fr`)"
      - "traefik.http.services.jenkinsservice.loadbalancer.server.port=8080"

  sonarqube:
    image: sonarqube
    volumes:
      - /etc/sonarqube/sonarqube_conf:/opt/sonarqube/conf
      - /etc/sonarqube/sonarqube_data:/opt/sonarqube/data
      - /etc/sonarqube/sonarqube_extensions:/opt/sonarqube/extensions
      - /etc/sonarqube/sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    command:
      - -Dhttp.proxyHost=146.59.147.11
      - -Dhttp.proxyPort=3128
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarquberouter.rule=Host(`sonarqube.fulgen.fr`)"
      - "traefik.http.services.sonarqubeservice.loadbalancer.server.port=9000" 

  redoc:
    image: redocly/redoc
    volumes:
      - /etc/redoc/swagger.yml:/usr/share/nginx/html/swagger.yaml 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.redocrouter.rule=Host(`redoc.fulgen.fr`)"
      - "traefik.http.services.redocservice.loadbalancer.server.port=80" 
  
  swagger:
    image: swaggerapi/swagger-ui
    volumes:
      - /etc/swagger/swagger.yml:/app/swagger.json 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.swaggerrouter.rule=Host(`swagger.fulgen.fr`)"
      - "traefik.http.services.swaggerservice.loadbalancer.server.port=8080" 

  mongodb:
    image: mongo
    restart: always
    #port:
    #  - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: petitpanda
      MONGO_INITDB_ROOT_PASSWORD: Singeserieux!500
    labels:
      - "traefik.enable=true"
      #- "traefik.http.routers.mongodbrouter.rule=Host(`mongodb.fulgen.fr`)"
      #- "traefik.http.services.mongodb.loadbalancer.server.port=27017" 

  rabbitmq:
    image: 'docker.io/bitnami/rabbitmq:3.8-debian-10'
    #  restart: always
    #ports:
    #  - '4369:4369'
    #  - '5672:5672'
    #  - '25672:25672'
    #  - '15672:15672'
    #volumes:
    #  - '/etc/rabbitmq:/bitnami'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rabbitmqrouter.rule=Host(`rabbitmq.fulgen.fr`)"
      #- "traefik.http.services.redocservice.loadbalancer.server.port=80" 

  mercure:
    image: dunglas/mercure
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mercurerouter.rule=Host(`mercure.fulgen.fr`)"
      #- "traefik.http.services.mercurerouter.loadbalancer.server.port=80" 

