version: "3"
services:

  portainer:
    image: portainer/portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.http.routers.portainerrouter.rule=Host(`portainer.fulgen.fr`)"
      - "traefik.http.services.portainerservice.loadbalancer.server.port=9000"

  traefik:
    image: traefik:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/docker_mount/traefik/conf.d:/etc/traefik/conf.d
    network_mode: host
    command:
      - "--global.sendanonymoususage=false"   # deactivate data sending
      - "--global.checknewversion=false"      # deactivate update checking
      - "--accesslog=true"                    # access logs
      - "--api=true"                          # API on
      - "--api.insecure=true"                 # expose API on 8080
      - "--api.dashboard=true"                # activate dashboard
      - "--log.level=INFO"                    # activate logs
      - "--providers.docker=true"
      #- "--providers.docker.exposedbydefault=true" # ONLY for debug
      - "--providers.file.directory=/etc/traefik/conf.d/" # able to load configurations on folder (yaml and toml)
      - "--providers.file.watch=true"           # able to load dynamicaly configuration
      - "--entrypoints.web.address=:80"         # WEB entrypoint for 80
      - "--entrypoints.websecure.address=:443"  # WEBSECURE entrypoint for 443
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefikrouter.rule=Host(`traefik.fulgen.fr`)"
      - "traefik.http.services.traefikservice.loadbalancer.server.port=8080" 

  jenkins:
    image: jenkins/jenkins
    restart: always
    volumes:
      - /etc/jenkins:/var/jenkins_home 
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jenkinsrouter.entrypoints=web"
      - "traefik.http.routers.jenkinsrouter.rule=Host(`jenkins.fulgen.fr`)"
      - "traefik.http.services.jenkinsservice.loadbalancer.server.port=8080"

  sonarqube:
    image: sonarqube
    restart: always
    volumes:
      - /etc/sonarqube/sonarqube_conf:/opt/sonarqube/conf
      - /etc/sonarqube/sonarqube_data:/opt/sonarqube/data
      - /etc/sonarqube/sonarqube_extensions:/opt/sonarqube/extensions
      - /etc/sonarqube/sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    command:
      - -Dhttp.proxyHost=146.59.147.11
      - -Dhttp.proxyPort=3128
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarquberouter.rule=Host(`sonarqube.fulgen.fr`)"
      - "traefik.http.services.sonarqubeservice.loadbalancer.server.port=9000" 

  #redoc:
  #  image: redocly/redoc
  #  restart: always
  #  volumes:
  #    - /etc/redoc/swagger.yml:/usr/share/nginx/html/swagger.yaml 
  #  labels:
  #    - "traefik.enable=true"
  #    - "traefik.http.routers.redocrouter.rule=Host(`redoc.fulgen.fr`)"
  #    - "traefik.http.services.redocservice.loadbalancer.server.port=80" 
  
  ### soon swagger
  #swagger:
  #  image: swaggerapi/swagger-ui
  #  volumes:
  #    - /etc/swagger/swagger.yml:/app/swagger.json 
  #  labels:
  #    - "traefik.enable=true"
  #    - "traefik.http.routers.swaggerrouter.rule=Host(`swagger.fulgen.fr`)"
  #    - "traefik.http.services.swaggerservice.loadbalancer.server.port=8080" 

  mongodb:
    image: mongo
    restart: always
    # environnement, login and password
    labels:
      - "traefik.enable=true"
      # ONLY IF FRONT SERVICES ON IT - ONLY FOR DEV
      #- "traefik.http.routers.mongodbrouter.rule=Host(`mongodb.fulgen.fr`)"
      #- "traefik.http.services.mongodb.loadbalancer.server.port=27017" 

  rabbitmq:
    image: 'docker.io/bitnami/rabbitmq:3.8-debian-10'
    restart: always
    #volumes:
    #  - '/etc/rabbitmq:/bitnami'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rabbitmqrouter.rule=Host(`rabbitmq.fulgen.fr`)"
      # ONLY IF FRONT SERVICES ON IT - ONLY FOR DEV
      #- "traefik.http.services.redocservice.loadbalancer.server.port=80" 

  mercure:
    image: dunglas/mercure
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mercurerouter.rule=Host(`mercure.fulgen.fr`)"
      # ONLY IF FRONT SERVICES ON IT - ONLY FOR DEV
      #- "traefik.http.services.mercurerouter.loadbalancer.server.port=80" 

